# User Settings | Edit there as per required

title: 39
url: "https://Chocomintopia.github.io/"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    alpha

email: 
author: 39

# This description will show up in google search results
# (for index page) etc.
description: >
    

# This will what will show against &copy; in the footer
copyright: 世界観

# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: 

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    

about_footer: false

github_username: Chocomintopia

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id:  # GA Tracking ID

### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

kramdown:
  math_engine: katex

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
